version: '3.1'

services:
  db:
    container_name: duo_db
    image: postgres
    restart: on-failure
    ports:
      - 5433:5432
    volumes:
      - .docker/volumes/db:/var/lib/postgres
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: root1234
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: duo_adminer
    restart: on-failure
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: duo_db
    networks:
      - app-network
    depends_on:
      - db

  migrations:
    image: jlenon7/duogg-migrations:1.1.0
    container_name: duo_migrations
    environment:
      DB_CONNECTION: postgres
      DB_HOST: duo_db
      DB_PORT: ''
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_ROOT_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
