on: [pull_request]

name: CI-DUO

jobs:
  run_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DATABASE: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_ROOT_PASSWORD: root1234
        ports:
          - '5432'

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.14.2'
          registry-url: 'https://npm.pkg.github.com'
      - name: Configure ENV
        run: cp .env.example .env.testing
      - name: Installation
        run: yarn
      - name: Lint project
        run: yarn lint:fix
      - name: Test User
        run: yarn test:user
        env:
          CI: true
